include:
  - project: devis/templates
    file: '.template.yml'
    ref: latest

stages:
  - install
  - build

##
## An overide of sonar-scanner for npm is required
## .sonar-scanner does not support node
##
sonar-scanner:
  stage: .pre
  image: $DOCKER_BASE/node:lts
  extends: .sonar-scanner
  before_script:
    - npm config set registry $ARTIFACTORY/api/npm/npm/
    - npm i -g sonarqube-scanner

install:
  image: $DOCKER_BASE/node:16-alpine
  stage: install

  # DEVIS template wrapper for node jobs
  extends: .node-base

  script:
    - npm ci

  # SKip DEVIS template publish and pass metadata to future job to publish
  after_script: []

  artifacts:
    paths:
      - node_modules
      - $PIPELINE_INFO_DIR # pass metadata to future job to publish

build and publish:
  image: $DIND
  stage: build

  # DEVIS template wrapper for docker jobs
  extends: .docker-base
  services:
    - name: $DIND
      alias: docker
  script:
    - docker build --tag $DOCKER_IMAGE_NAME -f $CI_PROJECT_DIR/Linux_Installer/Dockerfile .
    - docker push $DOCKER_IMAGE_NAME
    - docker save -o webssh.tar $DOCKER_IMAGE_NAME
    - tar -czvf $EXPORT_DIR/webssh.tar.gz webssh.tar
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"